name: Generate and Commit CSV

on:
  workflow_dispatch: # enable manual trigger

jobs:
  generate-and-commit-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'data_collection'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pandas requests python-dotenv

      - name: Generate CSV
        env:
          URL: "https://data.smartplay.lcsd.gov.hk/rest/cms/api/v1/publ/contents/open-data/badminton/file"
          OUTPUT_PATH: "output/"
          TZ: "Asia/Hong_Kong"
        run: python "src/Badminton court list_5min.py"

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Add court snapshot [skip ci]" || exit 0
          git push
