name: Generate and Commit CSV

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  generate-and-commit-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pandas and requests
        run: pip install pandas requests

      - name: Run py script and generate CSV
        run: python Badminton court list_5min.py

      - name: Commit and Push files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add output/*
          
          # Check if any file changes. Prevent error
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add changes"
            git push origin HEAD:${{ github.ref }}
          fi
